"""add favorite table

Revision ID: 3d5b52f2dfeb
Revises: 1b395a0e667c
Create Date: 2015-11-16 17:12:00.011364

"""

# revision identifiers, used by Alembic.
revision = '3d5b52f2dfeb'
down_revision = '1b395a0e667c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('involved_type', sa.Integer(), nullable=True),
    sa.Column('involved_topic_id', sa.Integer(), nullable=True),
    sa.Column('involved_reply_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    ### end Alembic commands ###
