"""add node table

Revision ID: b66ec21fa51
Revises: 3b939679b47f
Create Date: 2015-11-10 16:40:06.890426

"""

# revision identifiers, used by Alembic.
revision = 'b66ec21fa51'
down_revision = '3b939679b47f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plane_id', sa.Integer(), nullable=True),
    sa.Column('topic_count', sa.Integer(), nullable=True),
    sa.Column('limit_reputation', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('thumb', sa.Text(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('custom_style', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node')
    ### end Alembic commands ###
